export default function loadLeaflet(): Promise<{
    default: typeof import("leaflet");
    transformation(a: number, b: number, c: number, d: number): import("leaflet").Transformation;
    transformation(coefficients: [number, number, number, number]): import("leaflet").Transformation;
    latLng(latitude: number, longitude: number, altitude?: number): import("leaflet").LatLng;
    latLng(coords: import("leaflet").LatLngTuple | [number, number, number] | import("leaflet").LatLngLiteral | {
        lat: number;
        lng: number;
        alt?: number | undefined;
    }): import("leaflet").LatLng;
    latLngBounds(southWest: import("leaflet").LatLngExpression, northEast: import("leaflet").LatLngExpression): import("leaflet").LatLngBounds;
    latLngBounds(latlngs: import("leaflet").LatLngExpression[]): import("leaflet").LatLngBounds;
    point(x: number, y: number, round?: boolean): import("leaflet").Point;
    point(coords: import("leaflet").PointTuple | {
        x: number;
        y: number;
    }): import("leaflet").Point;
    bounds(topLeft: import("leaflet").PointExpression, bottomRight: import("leaflet").PointExpression): import("leaflet").Bounds;
    bounds(points: import("leaflet").Point[] | import("leaflet").BoundsLiteral): import("leaflet").Bounds;
    gridLayer(options?: import("leaflet").GridLayerOptions): import("leaflet").GridLayer;
    tileLayer: typeof import("leaflet").tileLayer;
    imageOverlay(imageUrl: string, bounds: import("leaflet").LatLngBoundsExpression, options?: import("leaflet").ImageOverlayOptions): import("leaflet").ImageOverlay;
    svgOverlay(svgImage: string | SVGElement, bounds: import("leaflet").LatLngBoundsExpression, options?: import("leaflet").ImageOverlayOptions): import("leaflet").SVGOverlay;
    videoOverlay(video: string | string[] | HTMLVideoElement, bounds: import("leaflet").LatLngBoundsExpression, options?: import("leaflet").VideoOverlayOptions): import("leaflet").VideoOverlay;
    polyline<T extends import("geojson").GeometryObject = import("geojson").LineString | import("geojson").MultiLineString, P = any>(latlngs: import("leaflet").LatLngExpression[] | import("leaflet").LatLngExpression[][], options?: import("leaflet").PolylineOptions): import("leaflet").Polyline<T, P>;
    polygon<P = any>(latlngs: import("leaflet").LatLngExpression[] | import("leaflet").LatLngExpression[][] | import("leaflet").LatLngExpression[][][], options?: import("leaflet").PolylineOptions): import("leaflet").Polygon<P>;
    rectangle<P = any>(latLngBounds: import("leaflet").LatLngBoundsExpression, options?: import("leaflet").PolylineOptions): import("leaflet").Rectangle<P>;
    circleMarker<P = any>(latlng: import("leaflet").LatLngExpression, options?: import("leaflet").CircleMarkerOptions): import("leaflet").CircleMarker<P>;
    circle<P = any>(latlng: import("leaflet").LatLngExpression, options: import("leaflet").CircleMarkerOptions): import("leaflet").Circle<P>;
    circle<P = any>(latlng: import("leaflet").LatLngExpression, radius: number, options?: import("leaflet").CircleMarkerOptions): import("leaflet").Circle<P>;
    svg(options?: import("leaflet").RendererOptions): import("leaflet").SVG;
    canvas(options?: import("leaflet").RendererOptions): import("leaflet").Canvas;
    layerGroup<P = any>(layers?: import("leaflet").Layer[], options?: import("leaflet").LayerOptions): import("leaflet").LayerGroup<P>;
    featureGroup<P = any>(layers?: import("leaflet").Layer[], options?: import("leaflet").LayerOptions): import("leaflet").FeatureGroup<P>;
    geoJSON<P = any, G extends import("geojson").GeometryObject = import("geojson").Geometry>(geojson?: import("geojson").GeoJsonObject | import("geojson").GeoJsonObject[] | null, options?: import("leaflet").GeoJSONOptions<P, G> | null): import("leaflet").GeoJSON<P, G>;
    geoJson<P = any, G extends import("geojson").GeometryObject = import("geojson").Geometry>(geojson?: import("geojson").GeoJsonObject | import("geojson").GeoJsonObject[] | null, options?: import("leaflet").GeoJSONOptions<P, G> | null): import("leaflet").GeoJSON<P, G>;
    popup(latlng: import("leaflet").LatLngExpression, options?: import("leaflet").PopupOptions): import("leaflet").Popup;
    popup(options?: import("leaflet").PopupOptions, source?: import("leaflet").Layer): import("leaflet").Popup;
    tooltip(latlng: import("leaflet").LatLngExpression, options?: import("leaflet").TooltipOptions): import("leaflet").Tooltip;
    tooltip(options?: import("leaflet").TooltipOptions, source?: import("leaflet").Layer): import("leaflet").Tooltip;
    map(element: string | HTMLElement, options?: import("leaflet").MapOptions): import("leaflet").Map;
    icon(options: import("leaflet").IconOptions): import("leaflet").Icon;
    divIcon(options?: import("leaflet").DivIconOptions): import("leaflet").DivIcon;
    marker<P = any>(latlng: import("leaflet").LatLngExpression, options?: import("leaflet").MarkerOptions): import("leaflet").Marker<P>;
    noConflict(): any;
    version: string;
    Class: typeof import("leaflet").Class;
    Transformation: typeof import("leaflet").Transformation;
    LineUtil: typeof import("leaflet").LineUtil;
    PolyUtil: typeof import("leaflet").PolyUtil;
    DomUtil: typeof import("leaflet").DomUtil;
    PosAnimation: typeof import("leaflet").PosAnimation;
    CRS: typeof import("leaflet").CRS;
    Projection: typeof import("leaflet").Projection;
    LatLng: typeof import("leaflet").LatLng;
    LatLngBounds: typeof import("leaflet").LatLngBounds;
    Point: typeof import("leaflet").Point;
    Bounds: typeof import("leaflet").Bounds;
    Events: typeof import("leaflet").Events;
    MixinType: typeof import("leaflet").MixinType;
    Mixin: import("leaflet").MixinType;
    Evented: typeof import("leaflet").Evented;
    Draggable: typeof import("leaflet").Draggable;
    Layer: typeof import("leaflet").Layer;
    GridLayer: typeof import("leaflet").GridLayer;
    TileLayer: typeof import("leaflet").TileLayer;
    ImageOverlay: typeof import("leaflet").ImageOverlay;
    SVGOverlay: typeof import("leaflet").SVGOverlay;
    VideoOverlay: typeof import("leaflet").VideoOverlay;
    Path: typeof import("leaflet").Path;
    Polyline: typeof import("leaflet").Polyline;
    Polygon: typeof import("leaflet").Polygon;
    Rectangle: typeof import("leaflet").Rectangle;
    CircleMarker: typeof import("leaflet").CircleMarker;
    Circle: typeof import("leaflet").Circle;
    Renderer: typeof import("leaflet").Renderer;
    SVG: typeof import("leaflet").SVG;
    Canvas: typeof import("leaflet").Canvas;
    LayerGroup: typeof import("leaflet").LayerGroup;
    FeatureGroup: typeof import("leaflet").FeatureGroup;
    GeoJSON: typeof import("leaflet").GeoJSON;
    Control: typeof import("leaflet").Control;
    control: typeof import("leaflet").control;
    DivOverlay: typeof import("leaflet").DivOverlay;
    Popup: typeof import("leaflet").Popup;
    Tooltip: typeof import("leaflet").Tooltip;
    Handler: typeof import("leaflet").Handler;
    DomEvent: typeof import("leaflet").DomEvent;
    Map: typeof import("leaflet").Map;
    Icon: typeof import("leaflet").Icon;
    DivIcon: typeof import("leaflet").DivIcon;
    Marker: typeof import("leaflet").Marker;
    Browser: typeof import("leaflet").Browser;
    Util: typeof import("leaflet").Util;
    extend: typeof import("leaflet").Util["extend"];
    bind: typeof import("leaflet").Util["bind"];
    stamp: typeof import("leaflet").Util["stamp"];
    setOptions: typeof import("leaflet").Util["setOptions"];
}>;
